const mongoose = require('mongoose');
const models = require('./models.cjs');

mongoose.connect('mongodb://127.0.0.1:27017/vigilant_eye')
  .then(() => console.log('MongoDB connected'))
  .catch(err => console.error('MongoDB connection error:', err));

const vehicles = [
  {
    plate: 'AP27BB2359',
    owner_name: 'Ramesh Kumar',
    ownership: '1st Owner',
    rto_office: 'Ongole (AP27)',
    owner_contact: '+91 98480 22359',
    owner_address: 'Gopala Nagar, Ongole, Prakasam District, AP',
    rc_number: 'RC27BB2359A',
    brand: 'Hero',
    model: 'Passion Pro',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP27BB2359',
    chassis_no: 'CHSAP27BB2359',
    color: 'Red',
    registration_date: new Date('2018-05-15'),
    registration_validity: new Date('2033-05-14'),
    insurance_valid: true,
    insurance_expiry: new Date('2028-05-15'),
    puc_valid: true,
    puc_expiry: new Date('2027-11-15'),
    fitness_valid: true,
    fitness_expiry: new Date('2033-05-14'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'AP29SU7815',
    owner_name: 'Sai Kiran',
    ownership: '1st Owner',
    rto_office: 'Vijayawada (AP29)',
    owner_contact: '+91 99660 78150',
    owner_address: 'Benz Circle, Vijayawada, Krishna District, AP',
    rc_number: 'RC29SU7815B',
    brand: 'Ola',
    model: 'S1 Air',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Electric',
    engine_no: 'EVAP29SU7815',
    chassis_no: 'EVCHAP29SU7815',
    color: 'White',
    registration_date: new Date('2023-08-10'),
    registration_validity: new Date('2038-08-09'),
    insurance_valid: true,
    insurance_expiry: new Date('2028-08-10'),
    puc_valid: true,
    puc_expiry: new Date('2026-12-10'),
    fitness_valid: true,
    fitness_expiry: new Date('2038-08-09'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'TG29B9772',
    owner_name: 'Arjun Reddy',
    ownership: '2nd Owner',
    rto_office: 'Secunderabad (TG29)',
    owner_contact: '+91 88990 97720',
    owner_address: 'Begumpet, Secunderabad, Hyderabad, TG',
    rc_number: 'RCTG29B9772C',
    brand: 'Yamaha',
    model: 'FZ-S FI',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGTG29B9772',
    chassis_no: 'CHSTG29B9772',
    color: 'Black',
    registration_date: new Date('2020-04-18'),
    registration_validity: new Date('2035-04-17'),
    insurance_valid: true,
    insurance_expiry: new Date('2027-04-18'),
    puc_valid: true,
    puc_expiry: new Date('2026-10-18'),
    fitness_valid: true,
    fitness_expiry: new Date('2035-04-17'),
    road_tax_paid: true,
    pending_challans: 2,
    challan_amount: 2500,
    criminal_cases: ['Stolen Vehicle Case Filed (FIR: 142/2026)'],
    status: 'stolen',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'AP40AE1109',
    owner_name: 'Lakshmi Devi',
    ownership: '1st Owner',
    rto_office: 'Rajahmundry (AP40)',
    owner_contact: '+91 77020 11090',
    owner_address: 'Danavaipeta, Rajahmundry, East Godavari, AP',
    rc_number: 'RC40AE1109D',
    brand: 'Hero',
    model: 'Pleasure+',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP40AE1109',
    chassis_no: 'CHSAP40AE1109',
    color: 'Blue',
    registration_date: new Date('2021-11-20'),
    registration_validity: new Date('2036-11-19'),
    insurance_valid: true,
    insurance_expiry: new Date('2026-11-20'),
    puc_valid: true,
    puc_expiry: new Date('2027-05-20'),
    fitness_valid: true,
    fitness_expiry: new Date('2036-11-19'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'AP27AG1102',
    owner_name: 'Praveen Kumar',
    ownership: '2nd Owner',
    rto_office: 'Ongole (AP27)',
    owner_contact: '+91 94400 11020',
    owner_address: 'Santhanuthalapadu, Ongole Rural, Prakasam District, AP',
    rc_number: 'RC27AG1102E',
    brand: 'Hero',
    model: 'Passion Plus',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP27AG1102',
    chassis_no: 'CHSAP27AG1102',
    color: 'Black',
    registration_date: new Date('2008-01-10'),
    registration_validity: new Date('2023-01-09'),
    insurance_valid: true,
    insurance_expiry: new Date('2027-01-10'),
    puc_valid: false,
    puc_expiry: new Date('2024-06-10'),
    fitness_valid: true,
    fitness_expiry: new Date('2023-01-09'),
    road_tax_paid: false,
    pending_challans: 1,
    challan_amount: 500,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: true
  },
  {
    plate: 'AP39CZ2158',
    owner_name: 'Karthik Varma',
    ownership: '1st Owner',
    rto_office: 'Nellore (AP39)',
    owner_contact: '+91 81220 21580',
    owner_address: 'Vedayapalem, Nellore, SPSR Nellore District, AP',
    rc_number: 'RC39CZ2158F',
    brand: 'Honda',
    model: 'Activa 6G',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP39CZ2158',
    chassis_no: 'CHSAP39CZ2158',
    color: 'Grey',
    registration_date: new Date('2022-03-05'),
    registration_validity: new Date('2037-03-04'),
    insurance_valid: false,
    insurance_expiry: new Date('2025-03-05'),
    puc_valid: true,
    puc_expiry: new Date('2026-09-05'),
    fitness_valid: true,
    fitness_expiry: new Date('2037-03-04'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: true,
    duplicate_plate: false,
    suspicious: true
  },
  {
    plate: 'AP27AK3753',
    owner_name: 'Naveen Kumar',
    ownership: '1st Owner',
    rto_office: 'Ongole (AP27)',
    owner_contact: '+91 99080 37530',
    owner_address: 'Kothapatnam Road, Ongole, Prakasam District, AP',
    rc_number: 'RC27AK3753G',
    brand: 'Hero Honda',
    model: 'Splendor Plus',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP27AK3753',
    chassis_no: 'CHSAP27AK3753',
    color: 'Black',
    registration_date: new Date('2019-12-05'),
    registration_validity: new Date('2034-12-04'),
    insurance_valid: true,
    insurance_expiry: new Date('2027-12-05'),
    puc_valid: true,
    puc_expiry: new Date('2026-06-05'),
    fitness_valid: true,
    fitness_expiry: new Date('2034-12-04'),
    road_tax_paid: true,
    pending_challans: 1,
    challan_amount: 1000,
    criminal_cases: [],
    status: 'stolen',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'KA32EM3809',
    owner_name: 'Rohit Shetty',
    ownership: '2nd Owner',
    rto_office: 'Gulbarga (KA32)',
    owner_contact: '+91 91480 38090',
    owner_address: 'MSK Mill Road, Gulbarga, Karnataka',
    rc_number: 'RC32EM3809H',
    brand: 'Bajaj',
    model: 'Avenger Street 160',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGKA32EM3809',
    chassis_no: 'CHSKA32EM3809',
    color: 'Red',
    registration_date: new Date('2020-10-12'),
    registration_validity: new Date('2035-10-11'),
    insurance_valid: true,
    insurance_expiry: new Date('2028-10-12'),
    puc_valid: true,
    puc_expiry: new Date('2026-10-12'),
    fitness_valid: true,
    fitness_expiry: new Date('2035-10-11'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: ['Hit and Run Investigation (FIR: 88/2026)'],
    status: 'under_investigation',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: true
  },
  {
    plate: 'AP39RY1366',
    owner_name: 'Anusha Reddy',
    ownership: '1st Owner',
    rto_office: 'Guntur (AP39)',
    owner_contact: '+91 93930 13660',
    owner_address: 'Vidya Nagar, Guntur, Guntur District, AP',
    rc_number: 'RC39RY1366I',
    brand: 'Suzuki',
    model: 'Access 125',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP39RY1366',
    chassis_no: 'CHSAP39RY1366',
    color: 'White',
    registration_date: new Date('2017-06-15'),
    registration_validity: new Date('2032-06-14'),
    insurance_valid: false,
    insurance_expiry: new Date('2025-06-15'),
    puc_valid: false,
    puc_expiry: new Date('2024-12-15'),
    fitness_valid: false,
    fitness_expiry: new Date('2032-06-14'),
    road_tax_paid: false,
    pending_challans: 3,
    challan_amount: 3500,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: true,
    suspicious: true
  },
  {
    plate: 'TG07K2373',
    owner_name: 'Mohan Rao',
    ownership: '1st Owner',
    rto_office: 'Secunderabad (TG07)',
    owner_contact: '+91 98490 23730',
    owner_address: 'Kukatpally, Hyderabad, TG',
    rc_number: 'RCTG07K2373J',
    brand: 'Suzuki',
    model: 'Access 125',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGTG07K2373',
    chassis_no: 'CHSTG07K2373',
    color: 'Blue',
    registration_date: new Date('2015-02-10'),
    registration_validity: new Date('2020-02-09'),
    insurance_valid: false,
    insurance_expiry: new Date('2018-02-10'),
    puc_valid: false,
    puc_expiry: new Date('2018-08-10'),
    fitness_valid: false,
    fitness_expiry: new Date('2020-02-09'),
    road_tax_paid: false,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'AP40BL0837',
    owner_name: 'Koteswara Rao',
    ownership: '1st Owner',
    rto_office: 'Rajahmundry (AP40)',
    owner_contact: '+91 94940 08370',
    owner_address: 'Synergy Layout, Rajahmundry, East Godavari, AP',
    rc_number: 'RC40BL0837K',
    brand: 'Bajaj',
    model: 'Pulsar',
    vehicle_type: 'Two Wheeler',
    fuel_type: 'Petrol',
    engine_no: 'ENGAP40BL0837',
    chassis_no: 'CHSAP40BL0837',
    color: 'Black',
    registration_date: new Date('2022-09-01'),
    registration_validity: new Date('2037-08-31'),
    insurance_valid: true,
    insurance_expiry: new Date('2027-09-01'),
    puc_valid: true,
    puc_expiry: new Date('2027-03-01'),
    fitness_valid: true,
    fitness_expiry: new Date('2037-08-31'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  },
  {
    plate: 'AP27BB9999',
    owner_name: 'Ravi Shankar',
    ownership: '1st Owner',
    rto_office: 'Ongole (AP27)',
    owner_contact: '+91 98480 99990',
    owner_address: 'Cloughpet, Ongole, Prakasam District, AP',
    rc_number: 'RC27BB9999L',
    brand: 'Kia',
    model: 'Sonet',
    vehicle_type: 'Four Wheeler',
    fuel_type: 'Diesel',
    engine_no: 'ENGAP27BB9999',
    chassis_no: 'CHSAP27BB9999',
    color: 'White',
    registration_date: new Date('2023-01-15'),
    registration_validity: new Date('2038-01-14'),
    insurance_valid: true,
    insurance_expiry: new Date('2028-01-15'),
    puc_valid: true,
    puc_expiry: new Date('2027-07-15'),
    fitness_valid: true,
    fitness_expiry: new Date('2038-01-14'),
    road_tax_paid: true,
    pending_challans: 0,
    challan_amount: 0,
    criminal_cases: [],
    status: 'active',
    fake_plate: false,
    duplicate_plate: false,
    suspicious: false
  }
];

async function seed() {
  await models.Vehicle.deleteMany({});
  await models.Vehicle.insertMany(vehicles);
  console.log('Seeded vehicles successfully');

  const bcrypt = require('bcryptjs');
  const password = await bcrypt.hash('admin123', 10);
  await models.User.deleteMany({});
  
  const usersToSeed = [
    { email: 'admin@gmail.com', password, full_name: 'Super Admin', role: 'admin' },
    { email: 'onetown@ongole.com', password, full_name: 'Ongole I Town SHO', role: 'sho', badge_number: 'SHO_ONE_TOWN', phone: '+91 85922 86101', station_id: 'PS001' },
    { email: 'twotown@ongole.com', password, full_name: 'Ongole II Town SHO', role: 'sho', badge_number: 'SHO_TWO_TOWN', phone: '+91 85922 86201', station_id: 'PS002' },
    { email: 'taluka@ongole.com', password, full_name: 'Ongole Taluka SHO', role: 'sho', badge_number: 'SHO_TALUKA', phone: '+91 85922 86301', station_id: 'PS003' },
    { email: 'threetown@ongole.com', password, full_name: 'Ongole III Town SHO', role: 'sho', badge_number: 'SHO_THREE_TOWN', phone: '+91 85922 86401', station_id: 'PS004' },
    { email: 'chimakurthy@ongole.com', password, full_name: 'Chimakurthy SHO', role: 'sho', badge_number: 'SHO_CHIMAKURTHY', phone: '+91 85922 86501', station_id: 'PS005' },
    { email: 'kandukur@ongole.com', password, full_name: 'Kandukur SHO', role: 'sho', badge_number: 'SHO_KANDUKUR', phone: '+91 85922 86601', station_id: 'PS006' }
  ];
  await models.User.insertMany(usersToSeed);
  console.log('Seeded all admin and station user accounts successfully');

  mongoose.connection.close();
}

seed();
