/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedStationDashboardRouteImport } from './routes/_authenticated/station-dashboard'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPoliceStationsRouteImport } from './routes/_authenticated/police-stations'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedCheckpointsRouteImport } from './routes/_authenticated/checkpoints'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedVehiclesPlateRouteImport } from './routes/_authenticated/vehicles.$plate'
import { Route as AuthenticatedAlertsIdRouteImport } from './routes/_authenticated/alerts.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStationDashboardRoute =
  AuthenticatedStationDashboardRouteImport.update({
    id: '/station-dashboard',
    path: '/station-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliceStationsRoute =
  AuthenticatedPoliceStationsRouteImport.update({
    id: '/police-stations',
    path: '/police-stations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckpointsRoute =
  AuthenticatedCheckpointsRouteImport.update({
    id: '/checkpoints',
    path: '/checkpoints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesPlateRoute =
  AuthenticatedVehiclesPlateRouteImport.update({
    id: '/vehicles/$plate',
    path: '/vehicles/$plate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsIdRoute = AuthenticatedAlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/police-stations': typeof AuthenticatedPoliceStationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/search': typeof AuthenticatedSearchRoute
  '/station-dashboard': typeof AuthenticatedStationDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/vehicles/$plate': typeof AuthenticatedVehiclesPlateRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/police-stations': typeof AuthenticatedPoliceStationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/search': typeof AuthenticatedSearchRoute
  '/station-dashboard': typeof AuthenticatedStationDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/': typeof AuthenticatedIndexRoute
  '/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/vehicles/$plate': typeof AuthenticatedVehiclesPlateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRouteWithChildren
  '/_authenticated/checkpoints': typeof AuthenticatedCheckpointsRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/police-stations': typeof AuthenticatedPoliceStationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/station-dashboard': typeof AuthenticatedStationDashboardRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/alerts/$id': typeof AuthenticatedAlertsIdRoute
  '/_authenticated/vehicles/$plate': typeof AuthenticatedVehiclesPlateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/alerts'
    | '/checkpoints'
    | '/database'
    | '/history'
    | '/police-stations'
    | '/profile'
    | '/scanner'
    | '/search'
    | '/station-dashboard'
    | '/upload'
    | '/alerts/$id'
    | '/vehicles/$plate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/alerts'
    | '/checkpoints'
    | '/database'
    | '/history'
    | '/police-stations'
    | '/profile'
    | '/scanner'
    | '/search'
    | '/station-dashboard'
    | '/upload'
    | '/'
    | '/alerts/$id'
    | '/vehicles/$plate'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/alerts'
    | '/_authenticated/checkpoints'
    | '/_authenticated/database'
    | '/_authenticated/history'
    | '/_authenticated/police-stations'
    | '/_authenticated/profile'
    | '/_authenticated/scanner'
    | '/_authenticated/search'
    | '/_authenticated/station-dashboard'
    | '/_authenticated/upload'
    | '/_authenticated/'
    | '/_authenticated/alerts/$id'
    | '/_authenticated/vehicles/$plate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/station-dashboard': {
      id: '/_authenticated/station-dashboard'
      path: '/station-dashboard'
      fullPath: '/station-dashboard'
      preLoaderRoute: typeof AuthenticatedStationDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/police-stations': {
      id: '/_authenticated/police-stations'
      path: '/police-stations'
      fullPath: '/police-stations'
      preLoaderRoute: typeof AuthenticatedPoliceStationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkpoints': {
      id: '/_authenticated/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof AuthenticatedCheckpointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/$plate': {
      id: '/_authenticated/vehicles/$plate'
      path: '/vehicles/$plate'
      fullPath: '/vehicles/$plate'
      preLoaderRoute: typeof AuthenticatedVehiclesPlateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/$id': {
      id: '/_authenticated/alerts/$id'
      path: '/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AuthenticatedAlertsIdRouteImport
      parentRoute: typeof AuthenticatedAlertsRoute
    }
  }
}

interface AuthenticatedAlertsRouteChildren {
  AuthenticatedAlertsIdRoute: typeof AuthenticatedAlertsIdRoute
}

const AuthenticatedAlertsRouteChildren: AuthenticatedAlertsRouteChildren = {
  AuthenticatedAlertsIdRoute: AuthenticatedAlertsIdRoute,
}

const AuthenticatedAlertsRouteWithChildren =
  AuthenticatedAlertsRoute._addFileChildren(AuthenticatedAlertsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRouteWithChildren
  AuthenticatedCheckpointsRoute: typeof AuthenticatedCheckpointsRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPoliceStationsRoute: typeof AuthenticatedPoliceStationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStationDashboardRoute: typeof AuthenticatedStationDashboardRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVehiclesPlateRoute: typeof AuthenticatedVehiclesPlateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRouteWithChildren,
  AuthenticatedCheckpointsRoute: AuthenticatedCheckpointsRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPoliceStationsRoute: AuthenticatedPoliceStationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStationDashboardRoute: AuthenticatedStationDashboardRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVehiclesPlateRoute: AuthenticatedVehiclesPlateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
